---
# role: ansible-role-hosts
# file: molecule/resources/playbooks/verify.yml

- name: Verify
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: "Lookup short hostname"
      command: hostname
      changed_when: false
      register: hostname_short

    - name: "Assertions"
      assert:
        that:
          - "ansible_hostname in hostname_short.stdout"
